### ISSUE TITLE
FileDialog is empty

### ISSUE THREAD

**Issue by oco2000** [vpyk/emu80v4#7]
https://i.imgur.com/RCQYj6P.png

OS: Ubuntu 19.04 64-bit
Qt: 5.12.2

**Comment by oco2000** [comment]
Solution:
qt/qtPal.cpp, line 424
Add
        `fileDialog.setOption(QFileDialog::DontUseNativeDialog);`

**Comment by vpyk** [comment]
Thanks! This problem seems to appear in Qt 5.10 or 5.11. With 5.9 all works fine. Though I couldn't figure out how to fix it it for now. I don't like qt built-in dialog so i'll try to find the source of the problem.

**Comment by vpyk** [comment]
Fixed by commit 2dd8da0

**Comment by oco2000** [comment]
Thank you!
Just curious, how your changes in 2dd8da0 could fix the dialogs? I can't see any related code there.

**Comment by vpyk** [comment]
The specific feature in using QFileDialog in Emu80 is that it is called from QTimer event for now
(with interval = 0, resulting in idle state events). I suggested that it is not correct to handle
this events when a modal dialog window is shown and this may affect it in certain circumstances.

Probably, there were some changes in implementation of Qt main application loop since version
5.10 or 5.11 that had led to this issue.
